use_frameworks!

target 'PHHelloPrintLog_Example' do
  pod 'PHHelloPrintLog', :path => '../'

  target 'PHHelloPrintLog_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
